stages: [translation, translation-pull, version, build, deployment]

include:
  - component: gitlab.com/luucy/sdk/ci-components/crowdin_push@main
  - component: gitlab.com/luucy/sdk/ci-components/crowdin_pull@main
  - component: gitlab.com/luucy/sdk/ci-components/version_increment@main
  - component: gitlab.com/luucy/sdk/ci-components/build_try@main
  - component: gitlab.com/luucy/sdk/ci-components/build_publish@main
  - component: gitlab.com/luucy/sdk/ci-components/deployment@main
    inputs:
      environments: https://app.dev.dev.luucy.ch https://app.staging33.dev.luucy.ch 
    #   environments: LUUCY_DEPLOYMENT_ENVS

  