
variables:
  # Product ID as it's registered in the Marketplace
  # PRODUCT_ID: '225'
  # Gitlab GIT user config for pipeline
  GITLAB_GIT_USR_EMAIL: 'gitlab_pipeline@luucy.ch'
  GITLAB_GIT_USR_NAME: 'gitlab_pipeline'
  GITLAB_REGISTRY_URL: 'https://gitlab.com/api/v4/projects/43757880/packages/generic'

stages:
  - translation
  - version
  - build
  - update

dummy:
  stage: translation
  script: echo "Dummy job for merge-request so that the pipeline is triggered."
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

translation:
  stage: translation
  image: crowdin/cli
  script:
    - crowdin upload sources --token $CROWDIN_API_TOKEN --project-id $CROWDIN_PROJECT_ID
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

version_read:
  stage: version
  image: node:latest
  script:
    - |
        APP_NAME=$(node -p "require('./package.json').name")
        echo "Creating a new version of : $APP_NAME"
        echo "APP_NAME=$APP_NAME"  >> app_detail.env
        current_version=$(node -p "require('./package.json').version")
        new_version=$(echo "$current_version" | awk -F. '{$NF = $NF + 1;} 1' OFS=.)
        echo "New version: $new_version"
        echo "APP_VERSION=$new_version" >> app_detail.env
  artifacts:
    paths:
      - app_detail.env
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

build_app:
  stage: build
  image: node:latest
  script:
    - source app_detail.env
    - echo "Building the $APP_VERSION"
    - apt-get update
    - apt-get install -y jq
    - npm i -g luucy-cli
    - npm i
    - git config user.email "$GITLAB_GIT_USR_EMAIL"
    - git config user.name "$GITLAB_GIT_USR_NAME"
    - git status
    - git reset --hard
    - luucy scope build
    - luucy publish $APP_VERSION
    - echo "-------------"
    - export APP_FILE=$APP_NAME-$APP_VERSION.lpb 
    - echo "Checking the file:$APP_FILE"
    - |
        if [ ! -f bundles/$APP_FILE ]; then
            echo "File bundles/$APP_FILE does not exists!";
            exit -1;
        fi
    - echo "-------------"
    - echo "Uploading to the Package registry"
    - |
      upload_resp=$(curl $GITLAB_REGISTRY_URL/$APP_NAME/$APP_VERSION/$APP_FILE \
        --header "PRIVATE-TOKEN: $PACKAGE_REGISTRY_TOKEN" \
        --upload-file bundles/$APP_FILE)
    - upload_message=$(echo "$upload_resp" | jq -r '.message')
    - |
        if [[ "$upload_message" == "201 Created" ]]; then
            echo "Bundle $APP_FILE uploaded successfully";
        else
            echo "Error uploading bundle $APP_FILE: $upload_message!";
            exit -1;
        fi
    - git push -o ci.skip
    #  Pass the variables to the next phase
    - echo "APP_PATH=$APP_PATH" >> app_file.env
    - echo "APP_VERSION=$APP_VERSION" >> app_file.env
    - echo "APP_FILE=$APP_FILE" >> app_file.env
  artifacts:
    paths:
      - app_file.env
      - bundles/
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

update_app:
  stage: update
  image: node:latest
  script:
    - source app_file.env
    - echo "-------------"
    # Calling Luucy API /api/login to obtain a apiKey
    - echo "Login to Luucy"
    - apt-get update  
    - apt-get install -y jq
    - login_payload="{\"login\":\"$LUUCY_ORG_ADMIN_EMAIL\",\"password\":\"$LUUCY_ORG_ADMIN_PWD\", \"rememberMe\":\"true\"}"
    - |
        login_resp=$(curl $LUUCY_API_URL/login \
            --header 'Content-Type: application/json' \
            --data "$login_payload")
        apikey=$(echo "$login_resp" | jq -r '.apiKey')

    - echo "-------------"
    # Calling Luucy API /api/file to upload a new artifact file
    - curl -o "$APP_FILE" -u $ARTIFACTORY_CRED -sL "$APP_PATH"
    - echo "Upload file"
    
    - upload_response=$(curl -b apiKey2=$apikey $LUUCY_API_URL/file/ -F "file=@$APP_FILE")
    - fileId=$(echo "$upload_response" | jq -r '.id')
    - |
        if [[ -n $fileId && $fileId -gt 0 ]]; then
            echo "Artefact for $PRODUCT_ID was uploaded to Luucy successfully (id: $fileId)";
        else
            echo "Error uploading artefact for $PRODUCT_ID!";
            exit -1;
        fi
    - echo "-------------"
    # Calling Luucy API /api/plugin to update the plugin with a new artifact
    - echo "Update plugin"
    - update_payload="{\"productId\":\"$PRODUCT_ID\",\"version\":\"$APP_VERSION\", \"attachmentId\":\"$fileId\"}"
    - |
        update_resp=$(curl -b apiKey2=$apikey $LUUCY_API_URL/plugin/ \
        --header 'Content-Type: application/json' \
        --data "$update_payload")
    - updated_id=$(echo "$update_resp" | jq -r '.id')
    - |
        if [[ -n $updated_id && $updated_id -gt 0 ]]; then
            echo "Product $PRODUCT_ID updated successfully (id: $updated_id)";
        else
            echo "Error updating $PRODUCT_ID!";
            exit -1;
        fi
  rules:
    # - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - when: never