"base_url" : "https://api.crowdin.com"
"commit_message": "[ci skip]"

"preserve_hierarchy": true

files: [
 {
  "source" : "/i18n/en.ts",
  "dest": "/plugin/my-camera-views/en.ts",
  "translation" : "/i18n/%two_letters_code%.ts",
  "update_option": "update_as_unapproved",
  "labels" : [
      "my-camera-views"
    ]
 }
]